# Version du fichier docker-compose. Ici, on utilise la version 3.9 (compatible avec Docker 20.10+).
version: '3.9'

# Définition des réseaux personnalisés pour permettre la communication entre les conteneurs.
networks:
    laravel:

# Début de la configuration des services (conteneurs)
services:

    # Service pour le serveur web Nginx
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        image: nginx:stable
        container_name: nginx
        ports:
            - "8089:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd  # 👈 Ajouté ici
        links:
            - fpm
        networks:
            - laravel

    # Service pour PHP-FPM
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        volumes:
            - .:/var/www/html
        links:
            - db
        networks:
            - laravel

    # Service pour la base de données MySQL
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: data_base_test_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - laravel

    # Service pour phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_ARBITRARY: 0  # 👈 Désactive la possibilité de se connecter à d'autres serveurs
            PMA_AUTH_TYPE: cookie  # 👈 Forcer le login via formulaire
        ports:
            - "8081:80"  # Accès via http://localhost:8081
        depends_on:
            - db
        networks:
            - laravel
